version: '3.4'

services:
  load_balancer:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kavirtireshop
    networks:
      - kavirtire
    ports:
      - "4000:4000"
  kavirtireshop:
    image: kavirtireshop
    restart: always
    build:
      context: .
      dockerfile: KavirTire.Shop.Presentation/Dockerfile
#    ports:
#      - "5000:80"
    expose:
      - "80"
    depends_on:
      - redis
    networks:
      - kavirtire  
    deploy:
      replicas: 3
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redis-data:/data
    command: redis-server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - kavirtire
networks:
  kavirtire:
    driver: bridge