//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KavirTire.Shop.KavirTire.Shop.Plugins.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KavirTire.Shop.KavirTire.Shop.Plugins.Core.Resources.PluginResource", typeof(PluginResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partyid.
        /// </summary>
        public static string ActivityParty_PartyId {
            get {
                return ResourceManager.GetString("ActivityParty_PartyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_bankaccountcard.
        /// </summary>
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_barcode.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_orderid.
        /// </summary>
        public static string Barcode_Order {
            get {
                return ResourceManager.GetString("Barcode_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_productid.
        /// </summary>
        public static string Barcode_Product {
            get {
                return ResourceManager.GetString("Barcode_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_serialnumber.
        /// </summary>
        public static string Barcode_SerialNumber {
            get {
                return ResourceManager.GetString("Barcode_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_trackingcode.
        /// </summary>
        public static string Barcode_TrackingCode {
            get {
                return ResourceManager.GetString("Barcode_TrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_generalpolicy.
        /// </summary>
        public static string GeneralPolicy {
            get {
                return ResourceManager.GetString("GeneralPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_syncserviceaddress.
        /// </summary>
        public static string GeneralPolicy_SyncServiceAddress {
            get {
                return ResourceManager.GetString("GeneralPolicy_SyncServiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_ipg.
        /// </summary>
        public static string Ipg {
            get {
                return ResourceManager.GetString("Ipg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_amount.
        /// </summary>
        public static string OnlinePayment_Amount {
            get {
                return ResourceManager.GetString("OnlinePayment_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kavirbankaccountid.
        /// </summary>
        public static string OnlinePayment_BankAccount {
            get {
                return ResourceManager.GetString("OnlinePayment_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_customer.
        /// </summary>
        public static string OnlinePayment_Customer {
            get {
                return ResourceManager.GetString("OnlinePayment_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_description.
        /// </summary>
        public static string OnlinePayment_Description {
            get {
                return ResourceManager.GetString("OnlinePayment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_ipgid.
        /// </summary>
        public static string OnlinePayment_Ipg {
            get {
                return ResourceManager.GetString("OnlinePayment_Ipg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_onlinepayment.
        /// </summary>
        public static string OnlinePayment_LogicalName {
            get {
                return ResourceManager.GetString("OnlinePayment_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_bmsd_kv_onlinepayment_bmsd_kv_onlinepayme.
        /// </summary>
        public static string OnlinePayment_OnlinePaymentLog_Relation {
            get {
                return ResourceManager.GetString("OnlinePayment_OnlinePaymentLog_Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_orderid.
        /// </summary>
        public static string OnlinePayment_Order {
            get {
                return ResourceManager.GetString("OnlinePayment_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_paymentidentity.
        /// </summary>
        public static string OnlinePayment_PaymentIdentity {
            get {
                return ResourceManager.GetString("OnlinePayment_PaymentIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_postbankaccountid.
        /// </summary>
        public static string OnlinePayment_PostBankAccount {
            get {
                return ResourceManager.GetString("OnlinePayment_PostBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_quoteid.
        /// </summary>
        public static string OnlinePayment_Quote {
            get {
                return ResourceManager.GetString("OnlinePayment_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_refno.
        /// </summary>
        public static string OnlinePayment_RefNo {
            get {
                return ResourceManager.GetString("OnlinePayment_RefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_resno.
        /// </summary>
        public static string OnlinePayment_ResNo {
            get {
                return ResourceManager.GetString("OnlinePayment_ResNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_securepan.
        /// </summary>
        public static string OnlinePayment_SecurePan {
            get {
                return ResourceManager.GetString("OnlinePayment_SecurePan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_shopresno.
        /// </summary>
        public static string OnlinePayment_ShopResNo {
            get {
                return ResourceManager.GetString("OnlinePayment_ShopResNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_systemtraceno.
        /// </summary>
        public static string OnlinePayment_SystemTraceNo {
            get {
                return ResourceManager.GetString("OnlinePayment_SystemTraceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_details.
        /// </summary>
        public static string OnlinePaymentLog_Details {
            get {
                return ResourceManager.GetString("OnlinePaymentLog_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_errorcode.
        /// </summary>
        public static string OnlinePaymentLog_ErrorCode {
            get {
                return ResourceManager.GetString("OnlinePaymentLog_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_onlinepaymentlog.
        /// </summary>
        public static string OnlinePaymentLog_LogicalName {
            get {
                return ResourceManager.GetString("OnlinePaymentLog_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_logtype.
        /// </summary>
        public static string OnlinePaymentLog_LogType {
            get {
                return ResourceManager.GetString("OnlinePaymentLog_LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_message.
        /// </summary>
        public static string OnlinePaymentLog_Message {
            get {
                return ResourceManager.GetString("OnlinePaymentLog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_onlinepaymentid.
        /// </summary>
        public static string OnlinePaymentLog_OnlinePayment {
            get {
                return ResourceManager.GetString("OnlinePaymentLog_OnlinePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salesorder.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pricelevel.
        /// </summary>
        public static string PriceList {
            get {
                return ResourceManager.GetString("PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to defaultuomid.
        /// </summary>
        public static string Product_DefaultUnit {
            get {
                return ResourceManager.GetString("Product_DefaultUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to productid.
        /// </summary>
        public static string Product_Id {
            get {
                return ResourceManager.GetString("Product_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quote.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transactioncurrencyid.
        /// </summary>
        public static string Quote_Currency {
            get {
                return ResourceManager.GetString("Quote_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_expireddate.
        /// </summary>
        public static string Quote_ExpiredDate {
            get {
                return ResourceManager.GetString("Quote_ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to freightamount.
        /// </summary>
        public static string Quote_FreightAmount {
            get {
                return ResourceManager.GetString("Quote_FreightAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quoteid.
        /// </summary>
        public static string Quote_Id {
            get {
                return ResourceManager.GetString("Quote_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quote.
        /// </summary>
        public static string Quote_LogicalName {
            get {
                return ResourceManager.GetString("Quote_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customerid.
        /// </summary>
        public static string Quote_PotentialCustomer {
            get {
                return ResourceManager.GetString("Quote_PotentialCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pricelevelid.
        /// </summary>
        public static string Quote_PriceList {
            get {
                return ResourceManager.GetString("Quote_PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quotenumber.
        /// </summary>
        public static string Quote_QuoteNumber {
            get {
                return ResourceManager.GetString("Quote_QuoteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_registrationdate.
        /// </summary>
        public static string Quote_RegistrationDate {
            get {
                return ResourceManager.GetString("Quote_RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_shopid.
        /// </summary>
        public static string Quote_ShopId {
            get {
                return ResourceManager.GetString("Quote_ShopId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to totalamount.
        /// </summary>
        public static string Quote_TotalAmount {
            get {
                return ResourceManager.GetString("Quote_TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_totalamountwithouttaxbase.
        /// </summary>
        public static string Quote_TotalAmountWithoutTax {
            get {
                return ResourceManager.GetString("Quote_TotalAmountWithoutTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to totalamountlessfreight.
        /// </summary>
        public static string Quote_TotalPreFreightAmount {
            get {
                return ResourceManager.GetString("Quote_TotalPreFreightAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to totaltax.
        /// </summary>
        public static string Quote_TotalTax {
            get {
                return ResourceManager.GetString("Quote_TotalTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quoteclose.
        /// </summary>
        public static string QuoteClose {
            get {
                return ResourceManager.GetString("QuoteClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quotecloseid.
        /// </summary>
        public static string QuoteClose_Id {
            get {
                return ResourceManager.GetString("QuoteClose_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quoteid.
        /// </summary>
        public static string QuoteClose_QuoteId {
            get {
                return ResourceManager.GetString("QuoteClose_QuoteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject.
        /// </summary>
        public static string QuoteClose_Subject {
            get {
                return ResourceManager.GetString("QuoteClose_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quotedetail.
        /// </summary>
        public static string QuoteProduct_LogicalName {
            get {
                return ResourceManager.GetString("QuoteProduct_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to priceperunit.
        /// </summary>
        public static string QuoteProduct_PricePerUnit {
            get {
                return ResourceManager.GetString("QuoteProduct_PricePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to productid.
        /// </summary>
        public static string QuoteProduct_Product {
            get {
                return ResourceManager.GetString("QuoteProduct_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity.
        /// </summary>
        public static string QuoteProduct_Quantity {
            get {
                return ResourceManager.GetString("QuoteProduct_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quoteid.
        /// </summary>
        public static string QuoteProduct_Quote {
            get {
                return ResourceManager.GetString("QuoteProduct_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quote_details.
        /// </summary>
        public static string QuoteProduct_Qute_RelationShip {
            get {
                return ResourceManager.GetString("QuoteProduct_Qute_RelationShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uomid.
        /// </summary>
        public static string QuoteProduct_Unit {
            get {
                return ResourceManager.GetString("QuoteProduct_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statecode.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statuscode.
        /// </summary>
        public static string StatusReason {
            get {
                return ResourceManager.GetString("StatusReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_syncserviceaddress.
        /// </summary>
        public static string SyncServiceAddress {
            get {
                return ResourceManager.GetString("SyncServiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uom.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
    }
}
