//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KavirTire.Shop.Infrastructure.SyncService.CRM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CrmResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CrmResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KavirTire.Shop.Infrastructure.SyncService.CRM.Common.Resources.CrmResource", typeof(CrmResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partyid.
        /// </summary>
        internal static string ActivityParty_PartyId {
            get {
                return ResourceManager.GetString("ActivityParty_PartyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_bankaccountcard.
        /// </summary>
        internal static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_bankname.
        /// </summary>
        internal static string BankAccount_BankName {
            get {
                return ResourceManager.GetString("BankAccount_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_iban.
        /// </summary>
        internal static string BankAccount_Iban {
            get {
                return ResourceManager.GetString("BankAccount_Iban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_bankaccountcardid.
        /// </summary>
        internal static string BankAccount_Id {
            get {
                return ResourceManager.GetString("BankAccount_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_ipgid.
        /// </summary>
        internal static string BankAccount_Ipg {
            get {
                return ResourceManager.GetString("BankAccount_Ipg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_ispost.
        /// </summary>
        internal static string BankAccount_IsPost {
            get {
                return ResourceManager.GetString("BankAccount_IsPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_bankaccountcard.
        /// </summary>
        internal static string BankAccount_LogicalName {
            get {
                return ResourceManager.GetString("BankAccount_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_name.
        /// </summary>
        internal static string BankAccount_Name {
            get {
                return ResourceManager.GetString("BankAccount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_sequencenumber.
        /// </summary>
        internal static string BankAccount_SequenceNumber {
            get {
                return ResourceManager.GetString("BankAccount_SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_webfileid.
        /// </summary>
        internal static string BankAccount_WebFile {
            get {
                return ResourceManager.GetString("BankAccount_WebFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adx_identity_username.
        /// </summary>
        internal static string Contact_AdxUsername {
            get {
                return ResourceManager.GetString("Contact_AdxUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_confirmpurchasehistory.
        /// </summary>
        internal static string Contact_ConfirmPurchaseHistory {
            get {
                return ResourceManager.GetString("Contact_ConfirmPurchaseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstname.
        /// </summary>
        internal static string Contact_FirstName {
            get {
                return ResourceManager.GetString("Contact_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contactid.
        /// </summary>
        internal static string Contact_Id {
            get {
                return ResourceManager.GetString("Contact_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastname.
        /// </summary>
        internal static string Contact_LastName {
            get {
                return ResourceManager.GetString("Contact_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobilephone.
        /// </summary>
        internal static string Contact_MobilePhone {
            get {
                return ResourceManager.GetString("Contact_MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_nationalidbase.
        /// </summary>
        internal static string Contact_NationalId {
            get {
                return ResourceManager.GetString("Contact_NationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_postaladdressbase.
        /// </summary>
        internal static string Contact_PostalAddress {
            get {
                return ResourceManager.GetString("Contact_PostalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address1_postalcode.
        /// </summary>
        internal static string Contact_PostalCode {
            get {
                return ResourceManager.GetString("Contact_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_provincebase.
        /// </summary>
        internal static string Contact_Province {
            get {
                return ResourceManager.GetString("Contact_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to versionnumber.
        /// </summary>
        internal static string Contact_VersionNumber {
            get {
                return ResourceManager.GetString("Contact_VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statecode.
        /// </summary>
        internal static string Entity_Status {
            get {
                return ResourceManager.GetString("Entity_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statuscode.
        /// </summary>
        internal static string Entity_StatusReason {
            get {
                return ResourceManager.GetString("Entity_StatusReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_generalpolicy.
        /// </summary>
        internal static string GeneralPolicy {
            get {
                return ResourceManager.GetString("GeneralPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_applymaximumnumberofpurchases.
        /// </summary>
        internal static string GeneralPolicy_ApplyMaximumNumberOfPurchases {
            get {
                return ResourceManager.GetString("GeneralPolicy_ApplyMaximumNumberOfPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_applynumberofpurchaseitems.
        /// </summary>
        internal static string GeneralPolicy_ApplyNumberOfPurchaseItems {
            get {
                return ResourceManager.GetString("GeneralPolicy_ApplyNumberOfPurchaseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_applypurchaseintervalday.
        /// </summary>
        internal static string GeneralPolicy_ApplyPurchaseIntervalInDays {
            get {
                return ResourceManager.GetString("GeneralPolicy_ApplyPurchaseIntervalInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_expirequoteforactionmin.
        /// </summary>
        internal static string GeneralPolicy_ExpireQuoteForActionMin {
            get {
                return ResourceManager.GetString("GeneralPolicy_ExpireQuoteForActionMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_expireqouteforcookymin.
        /// </summary>
        internal static string GeneralPolicy_ExpireQuoteForCookieMin {
            get {
                return ResourceManager.GetString("GeneralPolicy_ExpireQuoteForCookieMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_generalpolicyid.
        /// </summary>
        internal static string GeneralPolicy_Id {
            get {
                return ResourceManager.GetString("GeneralPolicy_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_maximumnumberofpurchases.
        /// </summary>
        internal static string GeneralPolicy_MaximumNumberOfPurchases {
            get {
                return ResourceManager.GetString("GeneralPolicy_MaximumNumberOfPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_numberofpurchaseitems.
        /// </summary>
        internal static string GeneralPolicy_NumberOfPurchaseItems {
            get {
                return ResourceManager.GetString("GeneralPolicy_NumberOfPurchaseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_pricelistid.
        /// </summary>
        internal static string GeneralPolicy_PriceList {
            get {
                return ResourceManager.GetString("GeneralPolicy_PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_purchaseintervalday.
        /// </summary>
        internal static string GeneralPolicy_PurchaseIntervalInDays {
            get {
                return ResourceManager.GetString("GeneralPolicy_PurchaseIntervalInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_showprdonlyreltocar.
        /// </summary>
        internal static string GeneralPolicy_ShowProductsOnlyRelatedToCustomerCar {
            get {
                return ResourceManager.GetString("GeneralPolicy_ShowProductsOnlyRelatedToCustomerCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_inventoryitem.
        /// </summary>
        internal static string InventoryItem {
            get {
                return ResourceManager.GetString("InventoryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_inventoryitemid.
        /// </summary>
        internal static string InventoryItem_Id {
            get {
                return ResourceManager.GetString("InventoryItem_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_inventoryforsale.
        /// </summary>
        internal static string InventoryItem_InventoryForSale {
            get {
                return ResourceManager.GetString("InventoryItem_InventoryForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_product.
        /// </summary>
        internal static string InventoryItem_ProductId {
            get {
                return ResourceManager.GetString("InventoryItem_ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_reservedinventory.
        /// </summary>
        internal static string InventoryItem_ReservedInventory {
            get {
                return ResourceManager.GetString("InventoryItem_ReservedInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_warehouse.
        /// </summary>
        internal static string InventoryItem_Warehouse {
            get {
                return ResourceManager.GetString("InventoryItem_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_ipg.
        /// </summary>
        internal static string Ipg {
            get {
                return ResourceManager.GetString("Ipg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_acceptorid.
        /// </summary>
        internal static string Ipg_AcceptorId {
            get {
                return ResourceManager.GetString("Ipg_AcceptorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_banks.
        /// </summary>
        internal static string Ipg_Bank {
            get {
                return ResourceManager.GetString("Ipg_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_finishstophour.
        /// </summary>
        internal static string Ipg_FinishStopHour {
            get {
                return ResourceManager.GetString("Ipg_FinishStopHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_finishstopmin.
        /// </summary>
        internal static string Ipg_FinishStopMin {
            get {
                return ResourceManager.GetString("Ipg_FinishStopMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_ipgid.
        /// </summary>
        internal static string Ipg_Id {
            get {
                return ResourceManager.GetString("Ipg_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_name.
        /// </summary>
        internal static string Ipg_Name {
            get {
                return ResourceManager.GetString("Ipg_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_passphrase.
        /// </summary>
        internal static string Ipg_PassPhrase {
            get {
                return ResourceManager.GetString("Ipg_PassPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_password.
        /// </summary>
        internal static string Ipg_Password {
            get {
                return ResourceManager.GetString("Ipg_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_postbankaccountid.
        /// </summary>
        internal static string Ipg_PostBankAccount {
            get {
                return ResourceManager.GetString("Ipg_PostBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_returnurl.
        /// </summary>
        internal static string Ipg_ReturnUrl {
            get {
                return ResourceManager.GetString("Ipg_ReturnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_rsakeyvalue.
        /// </summary>
        internal static string Ipg_RSAKeyValue {
            get {
                return ResourceManager.GetString("Ipg_RSAKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_sequencenumber.
        /// </summary>
        internal static string Ipg_SequenceNumber {
            get {
                return ResourceManager.GetString("Ipg_SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_startstophour.
        /// </summary>
        internal static string Ipg_StartStopHour {
            get {
                return ResourceManager.GetString("Ipg_StartStopHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_startstopmin.
        /// </summary>
        internal static string Ipg_StartStopMin {
            get {
                return ResourceManager.GetString("Ipg_StartStopMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_terminalid.
        /// </summary>
        internal static string Ipg_TerminalId {
            get {
                return ResourceManager.GetString("Ipg_TerminalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_locationbase.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_locationbaseid.
        /// </summary>
        internal static string Location_Id {
            get {
                return ResourceManager.GetString("Location_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_name.
        /// </summary>
        internal static string Location_Name {
            get {
                return ResourceManager.GetString("Location_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_parentlocationbase.
        /// </summary>
        internal static string Location_ParentLocation {
            get {
                return ResourceManager.GetString("Location_ParentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_postcostcategory.
        /// </summary>
        internal static string Location_PostCostCategory {
            get {
                return ResourceManager.GetString("Location_PostCostCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to annotation.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documentbody.
        /// </summary>
        internal static string Note_DocumentBody {
            get {
                return ResourceManager.GetString("Note_DocumentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimetype.
        /// </summary>
        internal static string Note_DocumentMimeType {
            get {
                return ResourceManager.GetString("Note_DocumentMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to annotationid.
        /// </summary>
        internal static string Note_Id {
            get {
                return ResourceManager.GetString("Note_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objectid.
        /// </summary>
        internal static string Note_Object {
            get {
                return ResourceManager.GetString("Note_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salesorder.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customerid.
        /// </summary>
        internal static string Order_Customer {
            get {
                return ResourceManager.GetString("Order_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salesorderid.
        /// </summary>
        internal static string Order_Id {
            get {
                return ResourceManager.GetString("Order_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_registrationdate.
        /// </summary>
        internal static string Order_RegistrationDate {
            get {
                return ResourceManager.GetString("Order_RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_totalquantity.
        /// </summary>
        internal static string Order_TotalQuantity {
            get {
                return ResourceManager.GetString("Order_TotalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to versionnumber.
        /// </summary>
        internal static string Order_VersionNumber {
            get {
                return ResourceManager.GetString("Order_VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_personaldoc.
        /// </summary>
        internal static string PersonalDoc {
            get {
                return ResourceManager.GetString("PersonalDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_contact.
        /// </summary>
        internal static string PersonalDoc_Contact {
            get {
                return ResourceManager.GetString("PersonalDoc_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adx_portallanguage.
        /// </summary>
        internal static string PortalLanguage {
            get {
                return ResourceManager.GetString("PortalLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adx_portallanguageid.
        /// </summary>
        internal static string PortalLanguage_Id {
            get {
                return ResourceManager.GetString("PortalLanguage_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adx_lcid.
        /// </summary>
        internal static string PortalLanguage_LCID {
            get {
                return ResourceManager.GetString("PortalLanguage_LCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_postcostcategory.
        /// </summary>
        internal static string PostCostCategory {
            get {
                return ResourceManager.GetString("PostCostCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_postcostcategoryid.
        /// </summary>
        internal static string PostCostCategory_Id {
            get {
                return ResourceManager.GetString("PostCostCategory_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_name.
        /// </summary>
        internal static string PostCostCategory_Name {
            get {
                return ResourceManager.GetString("PostCostCategory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_tirepostcost.
        /// </summary>
        internal static string PostCostCategory_TirePostCost {
            get {
                return ResourceManager.GetString("PostCostCategory_TirePostCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pricelevel.
        /// </summary>
        internal static string PriceList {
            get {
                return ResourceManager.GetString("PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pricelevelid.
        /// </summary>
        internal static string PriceList_Id {
            get {
                return ResourceManager.GetString("PriceList_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string PriceList_Name {
            get {
                return ResourceManager.GetString("PriceList_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to productpricelevel.
        /// </summary>
        internal static string PriceListItem {
            get {
                return ResourceManager.GetString("PriceListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount.
        /// </summary>
        internal static string PriceListItem_Amount {
            get {
                return ResourceManager.GetString("PriceListItem_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to productpricelevelid.
        /// </summary>
        internal static string PriceListItem_Id {
            get {
                return ResourceManager.GetString("PriceListItem_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pricelevelid.
        /// </summary>
        internal static string PriceListItem_PriceListId {
            get {
                return ResourceManager.GetString("PriceListItem_PriceListId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to productid.
        /// </summary>
        internal static string PriceListItem_ProductId {
            get {
                return ResourceManager.GetString("PriceListItem_ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_firstimageid.
        /// </summary>
        internal static string Product_FirstImage {
            get {
                return ResourceManager.GetString("Product_FirstImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to productid.
        /// </summary>
        internal static string Product_Id {
            get {
                return ResourceManager.GetString("Product_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string Product_Name {
            get {
                return ResourceManager.GetString("Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_productimage.
        /// </summary>
        internal static string ProductImage {
            get {
                return ResourceManager.GetString("ProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_productimageid.
        /// </summary>
        internal static string ProductImage_Id {
            get {
                return ResourceManager.GetString("ProductImage_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_productid.
        /// </summary>
        internal static string ProductImage_Product {
            get {
                return ResourceManager.GetString("ProductImage_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_webfileid.
        /// </summary>
        internal static string ProductImage_WebFile {
            get {
                return ResourceManager.GetString("ProductImage_WebFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quote.
        /// </summary>
        internal static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quoteid.
        /// </summary>
        internal static string Quote_Id {
            get {
                return ResourceManager.GetString("Quote_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_vehicle.
        /// </summary>
        internal static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_custmer.
        /// </summary>
        internal static string Vehicle_Customer {
            get {
                return ResourceManager.GetString("Vehicle_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_vehicleid.
        /// </summary>
        internal static string Vehicle_Id {
            get {
                return ResourceManager.GetString("Vehicle_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_vehicleregchar.
        /// </summary>
        internal static string Vehicle_VehicleRegistrationCharacter {
            get {
                return ResourceManager.GetString("Vehicle_VehicleRegistrationCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_vehicleregnol.
        /// </summary>
        internal static string Vehicle_VehicleRegistrationNumberLeft {
            get {
                return ResourceManager.GetString("Vehicle_VehicleRegistrationNumberLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_vehicleregnom.
        /// </summary>
        internal static string Vehicle_VehicleRegistrationNumberMiddle {
            get {
                return ResourceManager.GetString("Vehicle_VehicleRegistrationNumberMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_vehicleregnor.
        /// </summary>
        internal static string Vehicle_VehicleRegistrationNumberRight {
            get {
                return ResourceManager.GetString("Vehicle_VehicleRegistrationNumberRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_vehicletype.
        /// </summary>
        internal static string Vehicle_VehicleType {
            get {
                return ResourceManager.GetString("Vehicle_VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_vehicletype.
        /// </summary>
        internal static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_vehicletypeid.
        /// </summary>
        internal static string VehicleType_Id {
            get {
                return ResourceManager.GetString("VehicleType_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_name.
        /// </summary>
        internal static string VehicleType_Name {
            get {
                return ResourceManager.GetString("VehicleType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_vehicletypeproduct.
        /// </summary>
        internal static string VehicleTypeProduct {
            get {
                return ResourceManager.GetString("VehicleTypeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_kv_vehicletypeproductid.
        /// </summary>
        internal static string VehicleTypeProduct_Id {
            get {
                return ResourceManager.GetString("VehicleTypeProduct_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_product.
        /// </summary>
        internal static string VehicleTypeProduct_Product {
            get {
                return ResourceManager.GetString("VehicleTypeProduct_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_type.
        /// </summary>
        internal static string VehicleTypeProduct_Type {
            get {
                return ResourceManager.GetString("VehicleTypeProduct_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmsd_vehicletype.
        /// </summary>
        internal static string VehicleTypeProduct_VehicleType {
            get {
                return ResourceManager.GetString("VehicleTypeProduct_VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adx_webfile.
        /// </summary>
        internal static string WebFile {
            get {
                return ResourceManager.GetString("WebFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adx_webfileid.
        /// </summary>
        internal static string WebFile_Id {
            get {
                return ResourceManager.GetString("WebFile_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adx_partialurl.
        /// </summary>
        internal static string WebFile_PartialUrl {
            get {
                return ResourceManager.GetString("WebFile_PartialUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adx_webpage.
        /// </summary>
        internal static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adx_copy.
        /// </summary>
        internal static string WebPage_CopyHtml {
            get {
                return ResourceManager.GetString("WebPage_CopyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adx_webpageid.
        /// </summary>
        internal static string WebPage_Id {
            get {
                return ResourceManager.GetString("WebPage_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adx_partialurl.
        /// </summary>
        internal static string WebPage_PartialUrl {
            get {
                return ResourceManager.GetString("WebPage_PartialUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adx_webpagelanguageid.
        /// </summary>
        internal static string WebPage_WebPageLanguage {
            get {
                return ResourceManager.GetString("WebPage_WebPageLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adx_websitelanguage.
        /// </summary>
        internal static string WebsiteLanguage {
            get {
                return ResourceManager.GetString("WebsiteLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adx_websitelanguageid.
        /// </summary>
        internal static string WebsiteLanguage_Id {
            get {
                return ResourceManager.GetString("WebsiteLanguage_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adx_portallanguageid.
        /// </summary>
        internal static string WebsiteLanguage_PortalLanguage {
            get {
                return ResourceManager.GetString("WebsiteLanguage_PortalLanguage", resourceCulture);
            }
        }
    }
}
